### PR TITLE
changed the theme

### PR DESCRIPTION
**Pull request by danielasakpa**
Crypto-Catalogue

### CODE REVIEW

**Comment by Suman373** [comment]
@danielasakpa  Looks great!!! Since you turned it to lighter theme, please try to change the table colors and bg too!

**Comment by danielasakpa** [comment]
[Link to website](https://cryptocatalogue-em2z6bj1o-iamsuman898-gmailcom.vercel.app/)

I have changed the colour and hover effect of the table. Also, I made the background white, the navbar and the footer black.

**Comment by Suman373** [comment]
@danielasakpa The **price change** , **24h change** and **market cap** colors are not in contrast. Fix needed

fixBanner

**Comment by danielasakpa** [comment]
I have made changes to The price change, 24h change and market cap colour.

**Pull request merged**
